-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: preload = "/home/popchu/Downloads/helloworld.jpg"

hl.config({
    wallpaper = {
        path = "/home/popchu/Downloads/helloworld.jpg",
        fit_mode = "fill",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output

-- TODO: manual review: splash = false

-- TODO: manual review: ipc = "on"
